BREED_CHOICES = [
    ("Abyssinian", "Abyssinian"),
    ("Bengal", "Bengal"),
    ("British Shorthair", "British Shorthair"),
    ("Maine Coon", "Maine Coon"),
    ("Persian", "Persian"),
    ("Ragdoll", "Ragdoll"),
    ("Russian Blue", "Russian Blue"),
    ("Siamese", "Siamese"),
    ("Sphynx", "Sphynx"),
    ("Beagle", "Beagle"),
    ("Border Collie", "Border Collie"),
    ("Corgi", "Corgi"),
    ("Dachshund", "Dachshund"),
    ("French Bulldog", "French Bulldog"),
    ("German Shepherd", "German Shepherd"),
    ("Golden Retriever", "Golden Retriever"),
    ("Labrador Retriever", "Labrador Retriever"),
    ("Poodle", "Poodle"),
    ("Yorkshire Terrier", "Yorkshire Terrier"),
    ("Budgerigar", "Budgerigar"),
    ("Cockatiel", "Cockatiel"),
    ("Canary", "Canary"),
    ("Guinea Pig", "Guinea Pig"),
    ("Hamster", "Hamster"),
    ("Chinchilla", "Chinchilla"),
    ("Goldfish", "Goldfish"),
    ("Betta", "Betta"),
    ("", "Without breed"),
    ("Other", "Other / remaining breeds"),
]
